spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:prod-db-server}:${DB_PORT:5432}/${DB_NAME:carcenter_prod}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

logging:
  level:
    com.carcenter: WARN
    org.springframework.security: ERROR
    org.mybatis: ERROR
    root: WARN

# JWT 프로덕션 시크릿 (환경변수로 설정 필요)
jwt:
  secret: ${JWT_SECRET}

# 운영 환경에서 Swagger 비활성화
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
