spring:
  datasource:
    url: jdbc:postgresql://dev-db-server:5432/carcenter_dev
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

logging:
  level:
    com.carcenter: INFO
    org.springframework.security: WARN
    org.mybatis: WARN
