spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:carcenter_local;DB_CLOSE_DELAY=-1
    username: sa
    password: 
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
  
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  
  sql:
    init:
      mode: always
      schema-locations: classpath:schema-h2.sql
      data-locations: classpath:data-h2.sql
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

logging:
  level:
    com.carcenter: DEBUG
    org.springframework.security: DEBUG
    org.mybatis: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# 로컬 환경에서 Swagger 활성화
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
